import './globals.css';
import { Head } from './components/Head';
import { Header } from './components/Header';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<Head />
			</head>
			<body>{children}</body>
		</html>
	);
}
